### ISSUE TITLE
TP

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/4a-isi3-tp2-2016-2017-groupe-2-petitcuenot-dolle#1]
👍 C'est vraiment bien pour une première itération, je n'ai rien à dire sur le code.

⚠️ Le rapport est très bien, complet et explique bien votre démarche. Mais bordel, la coloration syntaxique 😆 !

⚠️ Les noms de package en java, c'est toujours en minuscule

**Comment by JeremyDolle** [comment]
Corrections faites 👍

**Comment by Slashgear** [comment]
Alors, merci, mais les noms de packages sont toujours en majuscules sur github.
Rassure toi, je sais pourquoi.

Git n'est pas sensible à la casse pour les nom de fichier/dossier

Pour lui le fichier Example.java et example.java il n'y a pas de différence.
Si tu veux pouvoir le changer sur github, il faudra changer ton nom de packages au autre chose puis revenir au nom de départ sans majuscules

**Comment by JeremyDolle** [comment]
C'est fait, c'est bizarre comme problème 😄 
Du coup on a renommé tout ça !

**Comment by Slashgear** [comment]
Pour moi c'est tout bon 👍
